version: 2

updates:
  - package-ecosystem: npm
    schedule:
      interval: weekly
      day: sunday
    groups:
      npm-dependencies:
        patterns:
          - "*"
    directories:
      - "/**/*"
    commit-message:
      prefix: fix(dependabot)

  - package-ecosystem: github-actions
    schedule:
      interval: weekly
      day: sunday
    groups:
      github-actions-dependencies:
        patterns:
          - "*"
    # recursively check in all subdirectories, there are actions
    # references that are not within the .github/ or other root folders
    directories:
      - "/**/*"
    exclude-paths: # use .github-private workflows unaccessible to dependabot
      - "reusable-workflows/frontend-pr-workflow/workflow.yml"
      - ".github/workflows/frontend-deploy-workflow.yml"
      - ".github/workflows/frontend-pr-workflow.yml"
      - ".github/workflows/deep-purple-checks.yml"
    ignore:
      - dependency-name: "Typeform/ci-standard-checks"
      # ignore dependencies from private repos. This alone does not prevent
      # errors in dependabot, the "exclude-paths" is required as well
      - dependency-name: "Typeform/.github-private/actions/aws-auth"
      - dependency-name: "Typeform/deep-purple-action"
    commit-message:
      prefix: fix(dependabot)
