version: 2

updates:
  - package-ecosystem: npm
    schedule:
      interval: weekly
      day: sunday
    groups:
      dependencies:
        patterns:
          - "*"
    directories:
      - "/"
    commit-message:
      prefix: fix(dependabot)

  - package-ecosystem: github-actions
    schedule:
      interval: weekly
      day: sunday
    groups:
      dependencies:
        patterns:
          - "*"
    # recursively check in all subdirectories, there are actions
    # references that are not within the .github/ or other root folders
    directories:
      - "/"
    commit-message:
      prefix: fix(dependabot)

  - package-ecosystem: docker
    schedule:
      interval: weekly
      day: sunday
    groups:
      dependencies:
        patterns:
          - "*"
    directories:
      - "/"
    commit-message:
      prefix: fix(dependabot)
