name: "Combine Dependabots"

on:
  workflow_dispatch:
    inputs:
      REPOSITORY:
        required: true
        type: string
      BRANCH_NAME:
        required: true
        type: string
      PR_NAME:
        required: true
        type: string

jobs:
  combine-dependabots:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
          always-auth: true
          registry-url: "https://npm.pkg.github.com"
          scope: "@typeform"

      - name: Get yarn cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}-${{ hashFiles('.github/workflows/**.yml') }}

      - name: Install Node.js dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{secrets.GH_TOKEN}}

      - run: yarn combine-dependabots
        env:
          GITHUB_TOKEN: ${{secrets.GH_TOKEN}}
          REPOSITORY: ${{inputs.REPOSITORY}}
          BRANCH_NAME: ${{inputs.BRANCH_NAME}}
          PR_NAME: ${{inputs.PR_NAME}}
