name: 'Slack Deployment Notification'
description: 'Send deployment success or failure notifications to Slack with detailed information'
inputs:
  slack-channel:
    description: 'Slack channel ID for notifications (e.g., tfprod-deploy)'
    required: true
  app-name:
    description: 'Application name being deployed'
    required: true
  deployment-status:
    description: 'Deployment status: success or failure'
    required: true
  cdn-url:
    description: 'Public CDN URL for the deployed application'
    required: true
  github-sha:
    description: 'Git commit SHA'
    required: true
  github-actor:
    description: 'GitHub user who triggered the deployment'
    required: true
  github-ref-name:
    description: 'Git branch or tag name'
    required: true
  github-repository:
    description: 'Repository name (owner/repo)'
    required: true
  github-server-url:
    description: 'GitHub server URL'
    required: true
  github-run-id:
    description: 'GitHub Actions run ID'
    required: true
  SLACK_BOT_TOKEN:
    description: 'Slack OAuth token for posting messages'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
    
    - name: Get commit message
      id: commit
      shell: bash
      run: |
        COMMIT_MSG=$(git log -1 --pretty=%B ${{ inputs.github-sha }} 2>/dev/null || echo "Commit message unavailable")
        # Truncate to 100 chars and escape for JSON
        COMMIT_MSG=$(echo "$COMMIT_MSG" | head -c 100 | sed 's/"/\\"/g' | tr -d '\n')
        echo "message=$COMMIT_MSG" >> $GITHUB_OUTPUT
        echo "short_sha=$(echo ${{ inputs.github-sha }} | cut -c1-7)" >> $GITHUB_OUTPUT
    
    - name: Send success notification
      if: ${{ inputs.deployment-status == 'success' }}
      uses: slackapi/slack-github-action@v1.27.0
      with:
        channel-id: ${{ inputs.slack-channel }}
        payload: |
          {
            "text": "✅ Deployment Successful: ${{ inputs.app-name }}",
            "blocks": [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "✅ Deployment Successful",
                  "emoji": true
                }
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*App:*\n${{ inputs.app-name }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Environment:*\nProduction"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*CDN:*\n<${{ inputs.cdn-url }}|${{ inputs.cdn-url }}>"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Deployed by:*\n${{ inputs.github-actor }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Commit:*\n<${{ inputs.github-server-url }}/${{ inputs.github-repository }}/commit/${{ inputs.github-sha }}|${{ steps.commit.outputs.short_sha }}>"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Branch:*\n${{ inputs.github-ref-name }}"
                  }
                ]
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*Commit Message:*\n${{ steps.commit.outputs.message }}"
                }
              },
              {
                "type": "actions",
                "elements": [
                  {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "View Workflow"
                    },
                    "url": "${{ inputs.github-server-url }}/${{ inputs.github-repository }}/actions/runs/${{ inputs.github-run-id }}"
                  },
                  {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "View Commit"
                    },
                    "url": "${{ inputs.github-server-url }}/${{ inputs.github-repository }}/commit/${{ inputs.github-sha }}"
                  }
                ]
              }
            ]
          }
      env:
        SLACK_BOT_TOKEN: ${{ inputs.SLACK_BOT_TOKEN }}
    
    - name: Send failure notification
      if: ${{ inputs.deployment-status == 'failure' }}
      uses: slackapi/slack-github-action@v1.27.0
      with:
        channel-id: ${{ inputs.slack-channel }}
        payload: |
          {
            "text": "❌ Deployment Failed: ${{ inputs.app-name }}",
            "blocks": [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "❌ Deployment Failed",
                  "emoji": true
                }
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*App:*\n${{ inputs.app-name }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Environment:*\nProduction"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Failed at:*\nDeploy job"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Deployed by:*\n${{ inputs.github-actor }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Commit:*\n<${{ inputs.github-server-url }}/${{ inputs.github-repository }}/commit/${{ inputs.github-sha }}|${{ steps.commit.outputs.short_sha }}>"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Branch:*\n${{ inputs.github-ref-name }}"
                  }
                ]
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": ":warning: *Action Required:* Check the workflow logs for details."
                }
              },
              {
                "type": "actions",
                "elements": [
                  {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "View Logs"
                    },
                    "url": "${{ inputs.github-server-url }}/${{ inputs.github-repository }}/actions/runs/${{ inputs.github-run-id }}",
                    "style": "danger"
                  },
                  {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "View Commit"
                    },
                    "url": "${{ inputs.github-server-url }}/${{ inputs.github-repository }}/commit/${{ inputs.github-sha }}"
                  }
                ]
              }
            ]
          }
      env:
        SLACK_BOT_TOKEN: ${{ inputs.SLACK_BOT_TOKEN }}

branding:
  icon: 'message-circle'
  color: 'purple'
