name: Secrets Scan
description: 'Scan for secrets using Gitleaks'
inputs:
  docker-username:
    description: 'Docker Username'
    required: true
  docker-password:
    description: 'Docker Password'
    required: true
  docker-registry:
    description: 'Docker Registry'
    required: true
  gh-token:
    description: 'Github Token'
    required: true
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/secrets-scan.sh
      env:
        GH_TOKEN: ${{ inputs.gh-token }}
      shell: bash
