name: CI Standard Checks
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, edited, synchronize, reopened]
    branches:
      - main 
  

jobs:
  ci-standard-checks:
     # for private repositories use private runners
     # runs-on: [self-hosted, automated-checks]
     # for public repositories use public runners
    runs-on: [ubuntu-latest]

    steps:
      - name: Check Out Source Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: CI Standard Checks
        uses: Typeform/ci-standard-checks@v1
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
    
