name: Library checks & release

on:
  push:
    branches:
      - main
      - next
      - alpha
      - beta
  pull_request:
    branches:
      - main
   
env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  main:
    name: Run checks and deploy
    runs-on: [ci-universtal-scale-set]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Setup Node with Cache
        uses: Typeform/.github/shared-actions/setup-node-with-cache@main
        with:
          node-version: '20'
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Run linting and tests
        run: npx npm-run-all -p test lint

      - name: Build assets
        run: yarn build

      - name: Release master
        run: yarn semantic-release
