name: Send Deployment Event

# Please update the trigger of the workflow with what makes more for sense the current repository.
# The proposed trigger will need a package to be release so it will execute.

on:
  release:
    types: [released]

jobs:
  release:
    # for private repositories
    runs-on: [self-hosted, node-12, automated-checks]
    # for public repositories
    # runs-on: [ubuntu-latest]

    steps:
      - uses: Typeform/.github/shared-actions/send-deployment-event@master
        with:
          user-id: "16235864"
          event: "engineering_deploy"
          repository-slug: ${{ github.repository }}
          segment-deploy-key: ${{ secrets.DEPLOYMENT_SEGMENT_WRITE_KEY }}
          # if the repo is an internal facing tool, library, etc which Typeformers use to deliver product value,
          # please leave this as true
          # if the repo is a user facing application, service, infrastructure, etc that when deployed, is visible
          # directly by our users, please change to false. Please consider using this workflow, as the event might be
          # sent already by jarvis/tfcli.
          # is-internal-repository-deployment: false
          is-internal-repository-deployment: true

