name: "Generate persisted operations"

on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Set GitHub packages registry
        run: |
          npm config set '//npm.pkg.github.com/:_authToken' ${{ secrets.GH_TOKEN }}
          npm config set @typeform:registry https://npm.pkg.github.com/

      - name: Install only @typeform/generate-persisted-operations-manifest
        run: yarn add --no-lockfile --non-interactive --dev @typeform/generate-persisted-operations-manifest

      # - name: Generate Persisted Operations
      #   run: node node_modules/@typeform/generate-persisted-operations-manifest/dist/index.js

      # - name: List generated files
      #   run: |
      #     echo "Listing contents of ./generated directory:"
      #     ls -la generated

      # - name: Display persisted-query-manifest.json
      #   run: |
      #     echo "Contents of generated/persisted-query-manifest.json:"
      #     cat generated/persisted-query-manifest.json

      - name: List installed files of @typeform/generate-persisted-operations-manifest
        run: |
          echo "Contents of the package directory:"
          ls -lR node_modules/@typeform/generate-persisted-operations-manifest/dist
