name: "Generate persisted operations"

on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true

jobs:
  generate:
    runs-on: [self-hosted, ci-universal]
    env:
      GRAPHQL_ENDPOINTS: |
        https://graphqlbff.staging.internal.tfdev.typeform.tf
        https://graphqlbff.tfprod.internal.typeform.tf
        https://graphqlbff.tfprod.internal.eu.typeform.tf
        https://graphqlbff.tfprod.internal.eu-central-1.typeform.tf

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Set GitHub packages registry
        run: |
          npm config set '//npm.pkg.github.com/:_authToken' ${{ secrets.GH_TOKEN }}
          npm config set @typeform:registry https://npm.pkg.github.com/

      # - name: Check if GraphQL endpoints are reachable
      #   run: |
      #     mapfile -t ENDPOINTS <<< "${GRAPHQL_ENDPOINTS}"
      #     for url in "${ENDPOINTS[@]}"; do
      #       echo "Pinging $url..."
      #       curl_exit_code=0
      #       curl --max-time 10 "$url?runNumber=$GITHUB_RUN_NUMBER" || curl_exit_code=$?
      #       if [ $curl_exit_code -ne 0 ]; then
      #         echo "❌ Curl command failed with exit code $curl_exit_code"
      #         exit $curl_exit_code
      #       fi
      #     done

      - name: Install only @typeform/generate-persisted-operations-manifest
        run: yarn add --no-lockfile --non-interactive --dev @typeform/generate-persisted-operations-manifest

      - name: Generate Persisted Operations
        run: node node_modules/@typeform/generate-persisted-operations-manifest/dist/index.js

      - name: List generated files
        run: |
          echo "Listing contents of ./generated directory:"
          ls -la generated

      - name: Display persisted-query-manifest.json
        run: |
          echo "Contents of generated/persisted-query-manifest.json:"
          cat generated/persisted-query-manifest.json

      - name: Extract app name from package.json
        run: |
          echo "APP_NAME=$(jq -r '.name' package.json | sed 's/@typeform\///')" >> $GITHUB_ENV

      - name: Print extracted app name
        run: echo "Extracted APP_NAME is ${{ env.APP_NAME }}"

      - name: Upload manifest to internal allow list for all endpoints
        run: |
          mapfile -t ENDPOINTS <<< "${GRAPHQL_ENDPOINTS}"
          for url in "${ENDPOINTS[@]}"; do
            echo "Uploading manifest to $url/internal/operation-allow-list?deploymentRunNumber=$GITHUB_RUN_NUMBER&appName=${{env.APP_NAME}}"
            curl --fail --max-time 30 -X PATCH "$url/internal/operation-allow-list?deploymentRunNumber=$GITHUB_RUN_NUMBER&appName=${{env.APP_NAME}}" \
              -H "Content-Type: application/json" \
              --data-binary "@generated/persisted-query-manifest.json" \
            if [ $curl_exit_code -ne 0 ]; then
              echo "❌ Failed to upload manifest to $url with exit code $curl_exit_code"
            else
              echo "✅ Successfully uploaded to $url"
            fi
          done

          if [ $curl_exit_code -ne 0 ]; then
            echo "❌ One or more uploads failed, failing workflow"
            exit $curl_exit_code
          fi
          done
