name: Build & push multi-arch image

on:
  workflow_call:
    secrets:
      build-secrets:
        description: "Build secrets"
        required: false
    inputs:
      platforms:
        type: string
        description: "Specify the target platform for the build output"
        default: "linux/amd64,linux/arm64"
      dev-prefix:
        type: boolean
        description: "Include 'dev-' prefix on image tag, when pushing on non-main branches"
        default: true
      prefix:
        type: string
        description: "Include a prefix on the image tag"
        required: false
        default: ""
      file:
        type: string
        description: "Path to the Dockerfile"
        required: false
      service:
        description: "Name to tag the image"
        type: string
        required: true
      version:
        description: "Version to tag the image"
        type: string
        required: true
      build-args:
        description: "Build args"
        type: "string"
        required: false
      context:
        description: "Build context"
        type: string
        required: false
        default: "."
      labels:
        description: "Image labels"
        type: string
        required: false
env:
  VERSION: ${{ inputs.version }}
  VERSION_LATEST: latest
jobs:
  build:
    name: Build and push image
    runs-on: [ self-hosted, ci-base]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker context for Buildx
        run: docker context create builders
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          endpoint: builders
      - name: Set dev prefix on tag
        if: ${{ (inputs.dev-prefix) && (github.ref != 'refs/heads/main') }}
        run: echo "VERSION=$(echo dev-$VERSION)" >> $GITHUB_ENV
      - name: Set configured prefix on tag
        if: ${{ inputs.prefix != '' }}
        run: echo "VERSION=$(echo ${{inputs.prefix}}-$VERSION)" >> $GITHUB_ENV
      - name: Build and push images
        uses: docker/build-push-action@v6
        with:
          build-args: ${{ inputs.build-args }}
          context: ${{ inputs.context }}
          labels: ${{ inputs.labels }}
          platforms: ${{ inputs.platforms }}
          push: true
          tags: |
            ${{ vars.IMAGE_REGISTRY }}/${{ inputs.service }}:${{ env.VERSION }}
            ${{ vars.IMAGE_REGISTRY }}/${{ inputs.service }}:${{ github.sha }}
          secrets: ${{ secrets.build-secrets }}
          file: ${{ inputs.file }}
      - name: Set configured prefix on latest tag
        if: ${{ inputs.prefix != '' }}
        run: echo "VERSION_LATEST=$(echo ${{inputs.prefix}}-$VERSION_LATEST)" >> $GITHUB_ENV
      - name: Push latest image
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: docker/build-push-action@v6
        with:
          build-args: ${{ inputs.build-args }}
          context: ${{ inputs.context }}
          labels: ${{ inputs.labels }}
          platforms: ${{ inputs.platforms }}
          push: true
          tags: |
            ${{ vars.IMAGE_REGISTRY }}/${{ inputs.service }}:${{ env.VERSION_LATEST }}
          secrets: ${{ secrets.build-secrets }}
          file: ${{ inputs.file }}
