name: Build & push multi-arch image

on:
  workflow_call:
    secrets:
      ECR_REGISTRY:
        required: true
    inputs:
      service:
        type: string
        required: true

jobs:
  build:
    name: Build and push image
    runs-on: [ self-hosted, automated-checks-ephemeral ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: false
          tags: ${{ secrets.ECR_REGISTRY }}/${{ inputs.service }}:${{ github.run_id }}
