name: Build & push multi-arch image

on:
  workflow_call:
    secrets:
      build-args:
        description: "Build args"
        required: false
      repository:
        description: "Image repository"
        required: true
    inputs:
      service:
        description: "A name to tag the image"
        type: string
        required: true
      context:
        description: "Build context"
        type: string
        required: false
        default: "."
      labels:
        description: "Image labels"
        type: string
        required: false
        default: |
          com.typeform.service=${{ inputs.service }}
          com.typeform.${{ inputs.service }}.version=${{ github.run_id }}
          com.typeform.${{ inputs.service }}.git_commit=${{ github.sha }}

jobs:
  build:
    name: Build and push image
    runs-on: [ self-hosted, bear-ephemeral ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker context for Buildx
        run: docker context create builders
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          endpoint: builders
      - name: Build and push images
        uses: docker/build-push-action@v5
        with:
          build-args: ${{ secrets.build-args }}
          context: ${{ inputs.context }}
          labels: ${{ inputs.labels }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.repository }}/${{ inputs.service }}:${{ github.run_id }}
      - name: Push latest image
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: docker/build-push-action@v5
        with:
          build-args: ${{ secrets.build-args }}
          context: ${{ inputs.context }}
          labels: ${{ inputs.labels }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.repository }}/${{ inputs.service }}:latest
