name: Secrets Scan

on: [push, pull_request]

env:
  DOCKER_REGISTRY: 'quay.io'
  DOCKER_USERNAME: 'typeform+travis'
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  build:
    name: Secret scan
    runs-on: [ubuntu-latest]

    steps:
      - name: Check Out Source Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Login to Quay Docker Registry
        run: docker login -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD $DOCKER_REGISTRY

      - name: Run Gitleaks
        run: ./hooks/pre-commit