name: Secrets Scan

on: [push, pull_request]

env:
  DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  build:
    name: Secret scan
    runs-on: [ubuntu-latest]

    steps:
      - name: Check Out Source Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      # If this run was triggered by a pull request event, then checkout the head of the pull request instead of the merge commit.
      - run: git checkout HEAD^2
        if: ${{ github.event_name == 'pull_request' }} 

      - name: Login to Quay Docker Registry
        run: docker login -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD $DOCKER_REGISTRY

      - name: Run Gitleaks
        run: ./hooks/pre-commit