name: Secrets Scan

on: [push]

jobs:
  secrets-scan:
    name: Secrets scan
    runs-on: [ubuntu-latest]

    steps:
      - name: Check Out Source Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      
      - name: Secret detection
        uses: Typeform/.github/shared-actions/secret-detection@master
        with:
          docker-registry: ${{ secrets.DOCKER_REGISTRY }}
          docker-username: ${{ secrets.DOCKER_USERNAME }}
          docker-password: ${{ secrets.DOCKER_PASSWORD }}
          gh-token: ${{ secrets.GH_TOKEN }}
