name: Secrets Scan

on: [push]

jobs:
  secrets-scan:
    name: Secrets scan
    runs-on: [ubuntu-latest]

    steps:
      - name: Check Out Source Code
        uses: actions/checkout@v2
      
      - name: Secrets Scan
        uses: Typeform/.github/shared-actions/secrets-scan@SP-894-secret-detection-action
        with:
          docker-registry: ${{ secrets.DOCKER_REGISTRY }}
          docker-username: ${{ secrets.DOCKER_USERNAME }}
          docker-password: ${{ secrets.DOCKER_PASSWORD }}
          gh-token: ${{ secrets.GH_TOKEN }}
