name: Send Deployment Event

on:
  push:
    branches: seti-1020-libraries-not-reporting-correctly

jobs:
  release:
    runs-on: [ubuntu-latest]
    steps:
      - uses: Typeform/.github/shared-actions/send-deployment-event@seti-1020-libraries-not-reporting-correctly
        with:
          user-id: "16235864"
          event: "engineering_deploy"
          repository-slug: ${{ github.repository }}
          segment-deploy-key: ${{ secrets.DEPLOYMENT_SEGMENT_WRITE_KEY }}

